version: "3.8"

services:
  caddy:
    image: raidsimp-frontend:0.1.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  backend:
    image: raidsimp-backend:0.1.0
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./backend/sqlite:/app/sqlite
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

volumes:
  caddy_data:
    external: true
