version: "3.8"

services:
  caddy:
    image: raidsimp-frontend:0.1.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data

  backend:
    image: raidsimp-backend:0.1.0
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./backend/sqlite:/app/sqlite

volumes:
  caddy_data:
    external: true
