version: "3.8"

services:
  caddy:
    build: ./caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ./frontend/build:/srv

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend/sqlite:/app/sqlite

volumes:
  caddy_data:
    external: true
