version: "3.8"

services:
  raidsimp-backend:
    image: raidsimp-backend:1.4.0
    networks:
      - caddy-network
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./backend/sqlite:/app/sqlite
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

networks:
  caddy-network:
    external: true

volumes:
  caddy_data:
    external: true
