version: "3.8"

services:
  caddy:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./backend/sqlite:/app/sqlite

volumes:
  caddy_data:
    external: true
