/* tslint:disable */
/* eslint-disable */
/**
 * RaidSIMP OpenAPI Spec
 * Manage your raid teams, enhanced with data from the Blizzard API.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RealmDto
 */
export interface RealmDto {
    /**
     * 
     * @type {string}
     * @memberof RealmDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof RealmDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RealmDto
     */
    slug: string;
}

export function RealmDtoFromJSON(json: any): RealmDto {
    return RealmDtoFromJSONTyped(json, false);
}

export function RealmDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RealmDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
        'slug': json['slug'],
    };
}

export function RealmDtoToJSON(value?: RealmDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
        'slug': value.slug,
    };
}


