/* tslint:disable */
/* eslint-disable */
/**
 * RaidSIMP OpenAPI Spec
 * Manage your raid teams, enhanced with data from the Blizzard API.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateRaidTeamDto,
    CreateRaidTeamDtoFromJSON,
    CreateRaidTeamDtoToJSON,
    RaidTeam,
    RaidTeamFromJSON,
    RaidTeamToJSON,
    RenameRaidTeamDto,
    RenameRaidTeamDtoFromJSON,
    RenameRaidTeamDtoToJSON,
} from '../models';

export interface RaidTeamsControllerCreateRequest {
    createRaidTeamDto: CreateRaidTeamDto;
}

export interface RaidTeamsControllerGetOneRequest {
    id: string;
}

export interface RaidTeamsControllerRemoveRequest {
    id: string;
}

export interface RaidTeamsControllerRenameTeamRequest {
    id: string;
    renameRaidTeamDto: RenameRaidTeamDto;
}

/**
 * 
 */
export class RaidTeamsApi extends runtime.BaseAPI {

    /**
     * Create a new raid team.
     */
    async raidTeamsControllerCreateRaw(requestParameters: RaidTeamsControllerCreateRequest): Promise<runtime.ApiResponse<RaidTeam>> {
        if (requestParameters.createRaidTeamDto === null || requestParameters.createRaidTeamDto === undefined) {
            throw new runtime.RequiredError('createRaidTeamDto','Required parameter requestParameters.createRaidTeamDto was null or undefined when calling raidTeamsControllerCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/raid-teams`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRaidTeamDtoToJSON(requestParameters.createRaidTeamDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => RaidTeamFromJSON(jsonValue));
    }

    /**
     * Create a new raid team.
     */
    async raidTeamsControllerCreate(requestParameters: RaidTeamsControllerCreateRequest): Promise<RaidTeam> {
        const response = await this.raidTeamsControllerCreateRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get all existing raid teams.
     */
    async raidTeamsControllerGetAllRaw(): Promise<runtime.ApiResponse<Array<RaidTeam>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/raid-teams`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RaidTeamFromJSON));
    }

    /**
     * Get all existing raid teams.
     */
    async raidTeamsControllerGetAll(): Promise<Array<RaidTeam>> {
        const response = await this.raidTeamsControllerGetAllRaw();
        return await response.value();
    }

    /**
     * Get a specific raid team.
     */
    async raidTeamsControllerGetOneRaw(requestParameters: RaidTeamsControllerGetOneRequest): Promise<runtime.ApiResponse<RaidTeam>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling raidTeamsControllerGetOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/raid-teams/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => RaidTeamFromJSON(jsonValue));
    }

    /**
     * Get a specific raid team.
     */
    async raidTeamsControllerGetOne(requestParameters: RaidTeamsControllerGetOneRequest): Promise<RaidTeam> {
        const response = await this.raidTeamsControllerGetOneRaw(requestParameters);
        return await response.value();
    }

    /**
     * Delete a raid team.
     */
    async raidTeamsControllerRemoveRaw(requestParameters: RaidTeamsControllerRemoveRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling raidTeamsControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/raid-teams/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a raid team.
     */
    async raidTeamsControllerRemove(requestParameters: RaidTeamsControllerRemoveRequest): Promise<void> {
        await this.raidTeamsControllerRemoveRaw(requestParameters);
    }

    /**
     * Rename an existing raid team.
     */
    async raidTeamsControllerRenameTeamRaw(requestParameters: RaidTeamsControllerRenameTeamRequest): Promise<runtime.ApiResponse<RaidTeam>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling raidTeamsControllerRenameTeam.');
        }

        if (requestParameters.renameRaidTeamDto === null || requestParameters.renameRaidTeamDto === undefined) {
            throw new runtime.RequiredError('renameRaidTeamDto','Required parameter requestParameters.renameRaidTeamDto was null or undefined when calling raidTeamsControllerRenameTeam.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/raid-teams/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RenameRaidTeamDtoToJSON(requestParameters.renameRaidTeamDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => RaidTeamFromJSON(jsonValue));
    }

    /**
     * Rename an existing raid team.
     */
    async raidTeamsControllerRenameTeam(requestParameters: RaidTeamsControllerRenameTeamRequest): Promise<RaidTeam> {
        const response = await this.raidTeamsControllerRenameTeamRaw(requestParameters);
        return await response.value();
    }

}
