/* tslint:disable */
/* eslint-disable */
/**
 * RaidSIMP OpenAPI Spec
 * Manage your raid teams, enhanced with data from the Blizzard API.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    RealmDto,
    RealmDtoFromJSON,
    RealmDtoToJSON,
} from '../models';

export interface RealmsControllerGetAllRequest {
    region: string;
}

/**
 * 
 */
export class RealmsApi extends runtime.BaseAPI {

    /**
     * Get a list of realms in a region.
     */
    async realmsControllerGetAllRaw(requestParameters: RealmsControllerGetAllRequest): Promise<runtime.ApiResponse<Array<RealmDto>>> {
        if (requestParameters.region === null || requestParameters.region === undefined) {
            throw new runtime.RequiredError('region','Required parameter requestParameters.region was null or undefined when calling realmsControllerGetAll.');
        }

        const queryParameters: any = {};

        if (requestParameters.region !== undefined) {
            queryParameters['region'] = requestParameters.region;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/realms`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RealmDtoFromJSON));
    }

    /**
     * Get a list of realms in a region.
     */
    async realmsControllerGetAll(requestParameters: RealmsControllerGetAllRequest): Promise<Array<RealmDto>> {
        const response = await this.realmsControllerGetAllRaw(requestParameters);
        return await response.value();
    }

}
